name: agrilo
description: Agrilo
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  awesome_bottom_bar: ^1.2.4
  bloc: ^9.2.0
  dio: ^5.9.2
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  hugeicons: ^1.1.5
  image_picker: ^1.2.1
  intl: ^0.20.2
  logger: ^2.7.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.4
  toastification: ^3.0.3


dev_dependencies:
  bloc_lint: ^0.4.0
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.23
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true
